# Add the configurations to be managed by c8y-configuration-plugin

files = [
     {path = '/etc/tedge/plugins/modbus/modbus.toml', type='modbus'},
     {path = '/etc/tedge/plugins/modbus/devices.toml', type='modbus-devices'}
#    ,{ path = '/etc/tedge/tedge.toml' },
#    { path = '/etc/tedge/mosquitto-conf/c8y-bridge.conf', type = 'c8y-bridge.conf' },
#    { path = '/etc/tedge/mosquitto-conf/tedge-mosquitto.conf', type = 'tedge-mosquitto.conf' },
#    { path = '/etc/mosquitto/mosquitto.conf', type = 'mosquitto.conf' },
#    { path = '/etc/tedge/c8y/example.txt', type = 'example', user = 'tedge', group = 'tedge', mode = 0o444 }
]
