[[device]]
name="Test"
#type="Modbus-Thinedge"
address=1
ip="127.0.0.1"
port=502 #probably fixed to 502
protocol="TCP"

[[device.holdingregisters]]
number=0
startbit=0
nobits=16
multiplier=1
divisor=1
decimalshiftright=1
type="measurement"
templatestring="{\"sag_Temperature\":{\"T\":%% }}"

[[device.holdingregisters]]
number=1
startbit=0
nobits=16
multiplier=1
divisor=1
type="measurement"
templatestring="{\"sag_Pressure\":{\"P\":%% }}"